-- Renumber Service Points into the block allocated to this Registration Agency.
--
-- service_point.id has started at a hardcoded 20000000 on every instance, and is
-- published in RAiD metadata as identifier.owner.servicePoint, so two agencies
-- could mint Service Points that are indistinguishable in federated metadata.
--
-- ${servicePointIdStart} and ${servicePointIdBlockSize} are supplied by
-- ServicePointIdRangeConfig, which derives them from the agency's own ROR. An
-- agency with no allocated block fails before this migration runs, so the
-- placeholders are always resolved by the time we get here.
--
-- Everything below runs in one transaction: a failure leaves the database exactly
-- as it was rather than committing a half-applied renumbering.

-- Children follow their parent instead of being updated by hand. raid_archive is
-- the exception: V41 created it without a foreign key, so it is updated below.
alter table app_user
    drop constraint app_user_service_point_id_fkey,
    add constraint app_user_service_point_id_fkey
        foreign key (service_point_id) references service_point (id) on update cascade;

alter table raid
    drop constraint raid_service_point_id_fkey,
    add constraint raid_service_point_id_fkey
        foreign key (service_point_id) references service_point (id) on update cascade;

alter table user_authz_request
    drop constraint user_authz_request_service_point_id_fkey,
    add constraint user_authz_request_service_point_id_fkey
        foreign key (service_point_id) references service_point (id) on update cascade;

-- A GENERATED ALWAYS identity column rejects UPDATE outright ("column can only be
-- updated to DEFAULT"), so it is relaxed for the renumbering and restored after.
alter table service_point
    alter column id set generated by default;

do
$$
    declare
        v_start  bigint := ${servicePointIdStart};
        v_block  bigint := ${servicePointIdBlockSize};
        v_min    bigint;
        v_max    bigint;
        v_offset bigint;
    begin
        select min(id), max(id) into v_min, v_max from service_point;

        if v_min is null then
            raise notice 'No Service Points to renumber; sequence will start at %', v_start;
            return;
        end if;

        if v_min >= v_start and v_max < v_start + v_block then
            raise notice 'Service Points % to % are already within the allocated block; nothing to renumber',
                v_min, v_max;
            return;
        end if;

        -- Anchor the lowest id at the start of the block. Differences between ids
        -- are preserved, so existing gaps survive and referenced values stay
        -- consistent. Blocks are far enough apart that the source and target
        -- ranges never overlap, so a single statement cannot collide on the
        -- primary key.
        v_offset := v_start - v_min;

        raise notice 'Renumbering % Service Points by % into block starting at %',
            (select count(*) from service_point), v_offset, v_start;

        update service_point set id = id + v_offset;

        -- No foreign key, so the cascade above does not reach it.
        update raid_archive
        set service_point_id = service_point_id + v_offset;

        -- The id is also embedded in each stored RAiD document.
        update raid
        set metadata = jsonb_set(
                metadata,
                '{identifier,owner,servicePoint}',
                to_jsonb((metadata -> 'identifier' -> 'owner' ->> 'servicePoint')::bigint + v_offset))
        where metadata -> 'identifier' -> 'owner' ? 'servicePoint';

        update raid_archive
        set metadata = jsonb_set(
                metadata,
                '{identifier,owner,servicePoint}',
                to_jsonb((metadata -> 'identifier' -> 'owner' ->> 'servicePoint')::bigint + v_offset))
        where metadata -> 'identifier' -> 'owner' ? 'servicePoint';
    end
$$;

alter table service_point
    alter column id set generated always;

-- Continue from the renumbered ids, or seed a fresh instance at its block start.
do
$$
    declare
        v_next bigint;
    begin
        select coalesce(max(id) + 1, ${servicePointIdStart}) into v_next from service_point;
        execute format('alter table service_point alter column id restart with %s', v_next);
    end
$$;

-- Adding the constraint validates every existing row, so this both prevents future
-- out-of-block inserts and asserts that the renumbering above landed correctly. A
-- failure here rolls the whole migration back.
--
-- Reallocating an agency's block later requires a migration to drop and recreate
-- this constraint.
alter table service_point
    add constraint service_point_id_within_allocated_block
        check (id >= ${servicePointIdStart}
            and id < ${servicePointIdStart} + ${servicePointIdBlockSize});

-- The cascade and the explicit updates above are only correct if every referencing
-- row still points at a Service Point, and if no stored document disagrees with the
-- row it belongs to.
do
$$
    declare
        v_orphans   bigint;
        v_mismatched bigint;
    begin
        select count(*) into v_orphans from raid_archive a
        where not exists (select 1 from service_point sp where sp.id = a.service_point_id);

        if v_orphans > 0 then
            raise exception 'Renumbering left % raid_archive rows referencing a Service Point that does not exist',
                v_orphans;
        end if;

        select count(*) into v_mismatched from raid
        where metadata -> 'identifier' -> 'owner' ? 'servicePoint'
          and (metadata -> 'identifier' -> 'owner' ->> 'servicePoint')::bigint <> service_point_id;

        if v_mismatched > 0 then
            raise exception 'Renumbering left % raid rows whose metadata servicePoint disagrees with service_point_id',
                v_mismatched;
        end if;
    end
$$;
